import { User, AttendanceRecord, Incident } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "usr-001",
    name: "Admin Principal",
    email: "admin@brigadapp.edu",
    password: "admin123",
    role: "admin",
    active: true,
    createdAt: "2024-01-10",
  },
  {
    id: "usr-002",
    name: "Coordinadora López",
    email: "coord@brigadapp.edu",
    password: "coord123",
    role: "coordinator",
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "usr-003",
    name: "Carlos Mendoza",
    email: "carlos@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "5°",
    section: "A",
    studentCode: "2024-001",
    active: true,
    createdAt: "2024-02-01",
  },
  {
    id: "usr-004",
    name: "María Fernández",
    email: "maria@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "5°",
    section: "B",
    studentCode: "2024-002",
    active: true,
    createdAt: "2024-02-01",
  },
  {
    id: "usr-005",
    name: "José Ramírez",
    email: "jose@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "6°",
    section: "A",
    studentCode: "2024-003",
    active: true,
    createdAt: "2024-02-05",
  },
  {
    id: "usr-006",
    name: "Ana Torres",
    email: "ana@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "6°",
    section: "B",
    studentCode: "2024-004",
    active: true,
    createdAt: "2024-02-05",
  },
  {
    id: "usr-007",
    name: "Luis Castillo",
    email: "luis@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "4°",
    section: "A",
    studentCode: "2024-005",
    active: false,
    createdAt: "2024-02-10",
  },
  {
    id: "usr-008",
    name: "Sofia Vega",
    email: "sofia@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "4°",
    section: "C",
    studentCode: "2024-006",
    active: true,
    createdAt: "2024-02-12",
  },
  {
    id: "usr-009",
    name: "Diego Morales",
    email: "diego@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "3°",
    section: "A",
    studentCode: "2024-007",
    active: true,
    createdAt: "2024-02-15",
  },
  {
    id: "usr-010",
    name: "Valentina Cruz",
    email: "valentina@brigadapp.edu",
    password: "brig123",
    role: "brigadier",
    grade: "3°",
    section: "B",
    studentCode: "2024-008",
    active: true,
    createdAt: "2024-02-15",
  },
];

const today = new Date().toISOString().split("T")[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-001",
    studentId: "usr-003",
    studentName: "Carlos Mendoza",
    grade: "5°",
    section: "A",
    date: today,
    status: "present",
    registeredBy: "Coordinadora López",
    time: "07:30",
  },
  {
    id: "att-002",
    studentId: "usr-004",
    studentName: "María Fernández",
    grade: "5°",
    section: "B",
    date: today,
    status: "present",
    registeredBy: "Coordinadora López",
    time: "07:28",
  },
  {
    id: "att-003",
    studentId: "usr-005",
    studentName: "José Ramírez",
    grade: "6°",
    section: "A",
    date: today,
    status: "absent",
    registeredBy: "Coordinadora López",
    time: "07:35",
    notes: "No se presentó",
  },
  {
    id: "att-004",
    studentId: "usr-006",
    studentName: "Ana Torres",
    grade: "6°",
    section: "B",
    date: today,
    status: "late",
    registeredBy: "Coordinadora López",
    time: "07:55",
    notes: "Llegó tarde",
  },
  {
    id: "att-005",
    studentId: "usr-008",
    studentName: "Sofia Vega",
    grade: "4°",
    section: "C",
    date: today,
    status: "present",
    registeredBy: "Admin Principal",
    time: "07:25",
  },
  {
    id: "att-006",
    studentId: "usr-009",
    studentName: "Diego Morales",
    grade: "3°",
    section: "A",
    date: today,
    status: "present",
    registeredBy: "Admin Principal",
    time: "07:30",
  },
  {
    id: "att-007",
    studentId: "usr-010",
    studentName: "Valentina Cruz",
    grade: "3°",
    section: "B",
    date: today,
    status: "excused",
    registeredBy: "Admin Principal",
    time: "07:30",
    notes: "Permiso médico",
  },
  {
    id: "att-008",
    studentId: "usr-003",
    studentName: "Carlos Mendoza",
    grade: "5°",
    section: "A",
    date: yesterday,
    status: "present",
    registeredBy: "Coordinadora López",
    time: "07:30",
  },
  {
    id: "att-009",
    studentId: "usr-004",
    studentName: "María Fernández",
    grade: "5°",
    section: "B",
    date: yesterday,
    status: "absent",
    registeredBy: "Coordinadora López",
    time: "07:35",
  },
  {
    id: "att-010",
    studentId: "usr-005",
    studentName: "José Ramírez",
    grade: "6°",
    section: "A",
    date: yesterday,
    status: "present",
    registeredBy: "Coordinadora López",
    time: "07:28",
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc-001",
    title: "Pelea en el patio",
    description:
      "Dos estudiantes tuvieron un altercado físico durante el recreo.",
    type: "behavioral",
    severity: "high",
    reportedBy: "Carlos Mendoza",
    involvedStudents: ["usr-005", "usr-009"],
    date: today,
    time: "10:30",
    location: "Patio central",
    status: "in_progress",
    createdAt: today,
  },
  {
    id: "inc-002",
    title: "Estudiante con mareos",
    description:
      "La estudiante presentó mareos durante la formación matutina.",
    type: "medical",
    severity: "medium",
    reportedBy: "María Fernández",
    involvedStudents: ["usr-010"],
    date: today,
    time: "07:45",
    location: "Patio de formación",
    status: "resolved",
    resolution: "Se atendió en enfermería y se avisó a los padres.",
    createdAt: today,
  },
  {
    id: "inc-003",
    title: "Portón sin seguro",
    description: "El portón trasero se encontró sin seguro durante la mañana.",
    type: "safety",
    severity: "high",
    reportedBy: "Ana Torres",
    involvedStudents: [],
    date: yesterday,
    time: "06:55",
    location: "Portón trasero",
    status: "resolved",
    resolution: "Se reportó al personal de mantenimiento y se aseguró.",
    createdAt: yesterday,
  },
  {
    id: "inc-004",
    title: "Daño en mobiliario",
    description: "Se encontraron sillas rotas en el salón 204.",
    type: "other",
    severity: "low",
    reportedBy: "Diego Morales",
    involvedStudents: [],
    date: yesterday,
    time: "09:15",
    location: "Salón 204",
    status: "open",
    createdAt: yesterday,
  },
  {
    id: "inc-005",
    title: "Bullying verbal",
    description:
      "Se reportaron insultos repetidos hacia un compañero en el pasillo.",
    type: "behavioral",
    severity: "medium",
    reportedBy: "Sofia Vega",
    involvedStudents: ["usr-007"],
    date: yesterday,
    time: "11:00",
    location: "Pasillo primer piso",
    status: "closed",
    resolution: "Se habló con los involucrados y sus tutores.",
    createdAt: yesterday,
  },
];
